### ISSUE TITLE
Exception occurred in initializer `next` during start

### ISSUE THREAD

**Issue by krlicmuhamed** [actionhero/ah-next-plugin#64]
It seems as If I cant get enough of these errors, when I run `npm run dev` at root location api runs first but then unexpected error happens:
```
$ npm run dev

> anyplace@0.1.0 dev C:\Projects\AnyPlaceOld
> cd api && ts-node-dev --transpile-only --ignore-watch="../web" --no-deps --notify=false ./src/server.ts

Using ts-node version 8.10.2, typescript version 3.8.3
notice: pid: 5040 
notice: environment: development 
info: *** Starting Actionhero *** 
info: actionhero member 192.168.0.17 has joined the cluster
emerg: Exception occurred in initializer `next` during start 
emerg: Error with initializer step: "start"
emerg: TypeError: Cannot read property 'dev' of undefined
    at Next.start (C:\Projects\AnyPlaceOld\node_modules\ah-next-plugin\dist\initializers\next.js:32:38)
    at Object.startFunction (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:119:47)
    at Object.asyncWaterfall (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\modules\utils\asyncWaterfall.js:46:33)    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Process.start (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:195:13)
    at main (C:\Projects\AnyPlaceOld\api\src\server.ts:16:3)
notice: stopping process... 
notice: Stopping server: web
notice: Stopping server: websocket
notice: *** Actionhero Stopped ***
```

**Comment by evantahler** [comment]
This looks like you may be missing a needed configuration option.  Do you have all 3 of the blow?

```
// from src/config/next.ts
const env = process.env.NODE_ENV ? process.env.NODE_ENV : "development";

export const DEFAULT = {
  next: () => {
    return {
      enabled: true,
      dev: env === "development",
      quiet: false,
    };
  },
};
```

**Comment by evantahler** [comment]
It seems you are having trouble in general loading  your config.  Is there anyway you can create and share an example project that has the same problems?  They may be related to .js files (not .ts) or something to do with Windows... or both.

**Comment by evantahler** [comment]
bump! Any update @krlicmuhamed?

**Comment by evantahler** [comment]
Closing due to lack of response
